start_seed: 10000

environment_name: "GermanCredit"
environment_config: {}

model_initialization:
    use_diagonal_covs: False
    num_initial_components: 1
    prior_mean: 0.
    prior_scale: 10.
    initial_cov: 100.

gmmvi_runner_config:
    log_metrics_interval: 20

#  mmd_evaluation_config:
#    alpha: 20.
#    sample_dir: "/home/oleg/src/gmmvi_test/src/gmmvi/experiments/target_distributions/tests/german_credit10k.npy"

use_sample_database: True
max_database_size: 10000000
temperature: 1.


